version: "3.7"

services:
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3000:3000"
      - "5050:5050"
      - "6501:6379"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: "unless-stopped"
    networks:
      - backend
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
        - ./mongo-data:/data/db
        - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - backend
  redis:
    image: redis
    container_name: redis
    ports:
      - "6500:6379"
    hostname: redis
    networks:
      - backend
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8081:80"
      - "444:443"
    volumes:
      - ./nginx.conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/galileo-be.johnsonis.me/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/galileo-be.johnsonis.me/privkey.pem:/etc/ssl/certs/privkey.pem:ro
    depends_on:
      - server
    networks:
      - backend
    restart: "unless-stopped"

networks:
  backend:
    driver: bridge
  redis:
    driver: bridge

volumes:
  data:
    driver: local
